# Apache mod_proxy 모듈 활성화 및 my-site.conf Include
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so

# 우리의 리버스 프록시 VirtualHost 설정 로드
Include /usr/local/apache2/conf/extra/my-site.conf
